# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x11herminas.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"c\n\x0c\x42\x61tchRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x61taset\x18\x02 \x01(\t\x12\x1a\n\x12\x63ompressed_payload\x18\x03 \x01(\x0c\x12\x14\n\x0crecord_count\x18\x04 \x01(\r\"-\n\x08\x42\x61tchAck\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x12\x41gentConfigRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"B\n\x13\x41gentConfigResponse\x12\x13\n\x0byaml_config\x18\x01 \x01(\t\x12\x16\n\x0e\x63onfig_version\x18\x02 \x01(\t\"Q\n\x10HeartbeatRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12+\n\x07sent_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1f\n\x11HeartbeatResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x8b\x02\n\x05\x41gent\x12I\n\tShipBatch\x12\x1f.herminas.agent.v1.BatchRequest\x1a\x1b.herminas.agent.v1.BatchAck\x12_\n\x0eGetAgentConfig\x12%.herminas.agent.v1.AgentConfigRequest\x1a&.herminas.agent.v1.AgentConfigResponse\x12V\n\tHeartbeat\x12#.herminas.agent.v1.HeartbeatRequest\x1a$.herminas.agent.v1.HeartbeatResponseB\x1fZ\x1dherminas/kernel/proto/agentpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035herminas/kernel/proto/agentpb'
  _globals['_BATCHREQUEST']._serialized_start=67
  _globals['_BATCHREQUEST']._serialized_end=166
  _globals['_BATCHACK']._serialized_start=168
  _globals['_BATCHACK']._serialized_end=213
  _globals['_AGENTCONFIGREQUEST']._serialized_start=215
  _globals['_AGENTCONFIGREQUEST']._serialized_end=253
  _globals['_AGENTCONFIGRESPONSE']._serialized_start=255
  _globals['_AGENTCONFIGRESPONSE']._serialized_end=321
  _globals['_HEARTBEATREQUEST']._serialized_start=323
  _globals['_HEARTBEATREQUEST']._serialized_end=404
  _globals['_HEARTBEATRESPONSE']._serialized_start=406
  _globals['_HEARTBEATRESPONSE']._serialized_end=437
  _globals['_AGENT']._serialized_start=440
  _globals['_AGENT']._serialized_end=707
# @@protoc_insertion_point(module_scope)
