# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import common_pb2 as common__pb2
from . import dataplane_pb2 as dataplane__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dataplane_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataPlaneStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeployPipeline = channel.unary_unary(
                '/herminas.dataplane.v1.DataPlane/DeployPipeline',
                request_serializer=dataplane__pb2.PipelineSpec.SerializeToString,
                response_deserializer=dataplane__pb2.DeployResult.FromString,
                _registered_method=True)
        self.StopPipeline = channel.unary_unary(
                '/herminas.dataplane.v1.DataPlane/StopPipeline',
                request_serializer=dataplane__pb2.PipelineId.SerializeToString,
                response_deserializer=dataplane__pb2.StopResult.FromString,
                _registered_method=True)
        self.GetPipelineStats = channel.unary_unary(
                '/herminas.dataplane.v1.DataPlane/GetPipelineStats',
                request_serializer=dataplane__pb2.PipelineId.SerializeToString,
                response_deserializer=dataplane__pb2.PipelineStats.FromString,
                _registered_method=True)
        self.DeployModel = channel.unary_unary(
                '/herminas.dataplane.v1.DataPlane/DeployModel',
                request_serializer=dataplane__pb2.ModelSpec.SerializeToString,
                response_deserializer=dataplane__pb2.DeployResult.FromString,
                _registered_method=True)
        self.DeployRule = channel.unary_unary(
                '/herminas.dataplane.v1.DataPlane/DeployRule',
                request_serializer=dataplane__pb2.RuleSpec.SerializeToString,
                response_deserializer=dataplane__pb2.DeployResult.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/herminas.dataplane.v1.DataPlane/StreamEvents',
                request_serializer=dataplane__pb2.EventFilter.SerializeToString,
                response_deserializer=dataplane__pb2.Event.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/herminas.dataplane.v1.DataPlane/GetHealth',
                request_serializer=common__pb2.HealthRequest.SerializeToString,
                response_deserializer=common__pb2.HealthStatus.FromString,
                _registered_method=True)


class DataPlaneServicer:
    """Missing associated documentation comment in .proto file."""

    def DeployPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPipelineStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeployModel(self, request, context):
        """ONNX
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeployRule(self, request, context):
        """WASM
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """anomalies, DLQ
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataPlaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeployPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployPipeline,
                    request_deserializer=dataplane__pb2.PipelineSpec.FromString,
                    response_serializer=dataplane__pb2.DeployResult.SerializeToString,
            ),
            'StopPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.StopPipeline,
                    request_deserializer=dataplane__pb2.PipelineId.FromString,
                    response_serializer=dataplane__pb2.StopResult.SerializeToString,
            ),
            'GetPipelineStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPipelineStats,
                    request_deserializer=dataplane__pb2.PipelineId.FromString,
                    response_serializer=dataplane__pb2.PipelineStats.SerializeToString,
            ),
            'DeployModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployModel,
                    request_deserializer=dataplane__pb2.ModelSpec.FromString,
                    response_serializer=dataplane__pb2.DeployResult.SerializeToString,
            ),
            'DeployRule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployRule,
                    request_deserializer=dataplane__pb2.RuleSpec.FromString,
                    response_serializer=dataplane__pb2.DeployResult.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=dataplane__pb2.EventFilter.FromString,
                    response_serializer=dataplane__pb2.Event.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=common__pb2.HealthRequest.FromString,
                    response_serializer=common__pb2.HealthStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'herminas.dataplane.v1.DataPlane', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('herminas.dataplane.v1.DataPlane', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataPlane:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeployPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/herminas.dataplane.v1.DataPlane/DeployPipeline',
            dataplane__pb2.PipelineSpec.SerializeToString,
            dataplane__pb2.DeployResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/herminas.dataplane.v1.DataPlane/StopPipeline',
            dataplane__pb2.PipelineId.SerializeToString,
            dataplane__pb2.StopResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPipelineStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/herminas.dataplane.v1.DataPlane/GetPipelineStats',
            dataplane__pb2.PipelineId.SerializeToString,
            dataplane__pb2.PipelineStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeployModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/herminas.dataplane.v1.DataPlane/DeployModel',
            dataplane__pb2.ModelSpec.SerializeToString,
            dataplane__pb2.DeployResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeployRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/herminas.dataplane.v1.DataPlane/DeployRule',
            dataplane__pb2.RuleSpec.SerializeToString,
            dataplane__pb2.DeployResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/herminas.dataplane.v1.DataPlane/StreamEvents',
            dataplane__pb2.EventFilter.SerializeToString,
            dataplane__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/herminas.dataplane.v1.DataPlane/GetHealth',
            common__pb2.HealthRequest.SerializeToString,
            common__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
