# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import common_pb2 as common__pb2
from . import intelligence_pb2 as intelligence__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in intelligence_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IntelligenceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranslateNL = channel.unary_unary(
                '/herminas.intelligence.v1.Intelligence/TranslateNL',
                request_serializer=intelligence__pb2.NLQuery.SerializeToString,
                response_deserializer=intelligence__pb2.SQLCandidate.FromString,
                _registered_method=True)
        self.TrainModel = channel.unary_stream(
                '/herminas.intelligence.v1.Intelligence/TrainModel',
                request_serializer=intelligence__pb2.TrainRequest.SerializeToString,
                response_deserializer=intelligence__pb2.TrainProgress.FromString,
                _registered_method=True)
        self.ExportONNX = channel.unary_unary(
                '/herminas.intelligence.v1.Intelligence/ExportONNX',
                request_serializer=intelligence__pb2.ModelId.SerializeToString,
                response_deserializer=intelligence__pb2.ONNXArtifact.FromString,
                _registered_method=True)
        self.Forecast = channel.unary_unary(
                '/herminas.intelligence.v1.Intelligence/Forecast',
                request_serializer=intelligence__pb2.ForecastRequest.SerializeToString,
                response_deserializer=intelligence__pb2.ForecastResult.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/herminas.intelligence.v1.Intelligence/GetHealth',
                request_serializer=common__pb2.HealthRequest.SerializeToString,
                response_deserializer=common__pb2.HealthStatus.FromString,
                _registered_method=True)


class IntelligenceServicer:
    """Missing associated documentation comment in .proto file."""

    def TranslateNL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportONNX(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Forecast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntelligenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranslateNL': grpc.unary_unary_rpc_method_handler(
                    servicer.TranslateNL,
                    request_deserializer=intelligence__pb2.NLQuery.FromString,
                    response_serializer=intelligence__pb2.SQLCandidate.SerializeToString,
            ),
            'TrainModel': grpc.unary_stream_rpc_method_handler(
                    servicer.TrainModel,
                    request_deserializer=intelligence__pb2.TrainRequest.FromString,
                    response_serializer=intelligence__pb2.TrainProgress.SerializeToString,
            ),
            'ExportONNX': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportONNX,
                    request_deserializer=intelligence__pb2.ModelId.FromString,
                    response_serializer=intelligence__pb2.ONNXArtifact.SerializeToString,
            ),
            'Forecast': grpc.unary_unary_rpc_method_handler(
                    servicer.Forecast,
                    request_deserializer=intelligence__pb2.ForecastRequest.FromString,
                    response_serializer=intelligence__pb2.ForecastResult.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=common__pb2.HealthRequest.FromString,
                    response_serializer=common__pb2.HealthStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'herminas.intelligence.v1.Intelligence', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('herminas.intelligence.v1.Intelligence', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Intelligence:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TranslateNL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/herminas.intelligence.v1.Intelligence/TranslateNL',
            intelligence__pb2.NLQuery.SerializeToString,
            intelligence__pb2.SQLCandidate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/herminas.intelligence.v1.Intelligence/TrainModel',
            intelligence__pb2.TrainRequest.SerializeToString,
            intelligence__pb2.TrainProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportONNX(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/herminas.intelligence.v1.Intelligence/ExportONNX',
            intelligence__pb2.ModelId.SerializeToString,
            intelligence__pb2.ONNXArtifact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Forecast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/herminas.intelligence.v1.Intelligence/Forecast',
            intelligence__pb2.ForecastRequest.SerializeToString,
            intelligence__pb2.ForecastResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/herminas.intelligence.v1.Intelligence/GetHealth',
            common__pb2.HealthRequest.SerializeToString,
            common__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
