# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: intelligence.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'intelligence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12intelligence.proto\x12\x18herminas.intelligence.v1\x1a\x0c\x63ommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"G\n\x07NLQuery\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x18\n\x10\x61llowed_datasets\x18\x03 \x03(\t\"?\n\x0cSQLCandidate\x12\x0b\n\x03sql\x18\x01 \x01(\t\x12\x13\n\x0b\x65xplanation\x18\x02 \x01(\t\x12\r\n\x05valid\x18\x03 \x01(\x08\"\x15\n\x07ModelId\x12\n\n\x02id\x18\x01 \x01(\t\"3\n\x0cTrainRequest\x12\x0f\n\x07\x64\x61taset\x18\x01 \x01(\t\x12\x12\n\nmodel_type\x18\x02 \x01(\t\"A\n\rTrainProgress\x12\x10\n\x08progress\x18\x01 \x01(\x01\x12\r\n\x05stage\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"4\n\x0cONNXArtifact\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x12\n\nonnx_bytes\x18\x02 \x01(\x0c\"K\n\x0f\x46orecastRequest\x12\x0f\n\x07\x64\x61taset\x18\x01 \x01(\t\x12\x0e\n\x06metric\x18\x02 \x01(\t\x12\x17\n\x0fhorizon_minutes\x18\x03 \x01(\r\"P\n\x0e\x46orecastResult\x12\x0e\n\x06values\x18\x01 \x03(\x01\x12.\n\ntimestamps\x18\x02 \x03(\x0b\x32\x1a.google.protobuf.Timestamp2\xd5\x03\n\x0cIntelligence\x12X\n\x0bTranslateNL\x12!.herminas.intelligence.v1.NLQuery\x1a&.herminas.intelligence.v1.SQLCandidate\x12_\n\nTrainModel\x12&.herminas.intelligence.v1.TrainRequest\x1a\'.herminas.intelligence.v1.TrainProgress0\x01\x12W\n\nExportONNX\x12!.herminas.intelligence.v1.ModelId\x1a&.herminas.intelligence.v1.ONNXArtifact\x12_\n\x08\x46orecast\x12).herminas.intelligence.v1.ForecastRequest\x1a(.herminas.intelligence.v1.ForecastResult\x12P\n\tGetHealth\x12!.herminas.common.v1.HealthRequest\x1a .herminas.common.v1.HealthStatusB&Z$herminas/kernel/proto/intelligencepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intelligence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$herminas/kernel/proto/intelligencepb'
  _globals['_NLQUERY']._serialized_start=95
  _globals['_NLQUERY']._serialized_end=166
  _globals['_SQLCANDIDATE']._serialized_start=168
  _globals['_SQLCANDIDATE']._serialized_end=231
  _globals['_MODELID']._serialized_start=233
  _globals['_MODELID']._serialized_end=254
  _globals['_TRAINREQUEST']._serialized_start=256
  _globals['_TRAINREQUEST']._serialized_end=307
  _globals['_TRAINPROGRESS']._serialized_start=309
  _globals['_TRAINPROGRESS']._serialized_end=374
  _globals['_ONNXARTIFACT']._serialized_start=376
  _globals['_ONNXARTIFACT']._serialized_end=428
  _globals['_FORECASTREQUEST']._serialized_start=430
  _globals['_FORECASTREQUEST']._serialized_end=505
  _globals['_FORECASTRESULT']._serialized_start=507
  _globals['_FORECASTRESULT']._serialized_end=587
  _globals['_INTELLIGENCE']._serialized_start=590
  _globals['_INTELLIGENCE']._serialized_end=1059
# @@protoc_insertion_point(module_scope)
