// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: dataplane.proto

// Go control plane -> Rust data plane. Go is always the client here
// (cahier des charges §6.3); the Rust server lives in rust/protocol/.
//
// Only GetHealth has a real implementation as of M0.3 — it exists to prove
// the gRPC plumbing works end to end (protoc -> stubs in 3 languages ->
// real server -> real client -> latency benchmark). The rest are the
// contracts the pipeline manager (M3.2), ML deploy (M4.3) and WASM rules
// (M6.2) will implement against; calling them today returns UNIMPLEMENTED.

package dataplanepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	commonpb "herminas/kernel/proto/commonpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PipelineId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineId) Reset() {
	*x = PipelineId{}
	mi := &file_dataplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineId) ProtoMessage() {}

func (x *PipelineId) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineId.ProtoReflect.Descriptor instead.
func (*PipelineId) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{0}
}

func (x *PipelineId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PipelineSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	YamlConfig    string                 `protobuf:"bytes,3,opt,name=yaml_config,json=yamlConfig,proto3" json:"yaml_config,omitempty"` // declarative pipeline (F-201), parsed in M3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineSpec) Reset() {
	*x = PipelineSpec{}
	mi := &file_dataplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineSpec) ProtoMessage() {}

func (x *PipelineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineSpec.ProtoReflect.Descriptor instead.
func (*PipelineSpec) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{1}
}

func (x *PipelineSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PipelineSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PipelineSpec) GetYamlConfig() string {
	if x != nil {
		return x.YamlConfig
	}
	return ""
}

type DeployResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResult) Reset() {
	*x = DeployResult{}
	mi := &file_dataplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResult) ProtoMessage() {}

func (x *DeployResult) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResult.ProtoReflect.Descriptor instead.
func (*DeployResult) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{2}
}

func (x *DeployResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeployResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResult) Reset() {
	*x = StopResult{}
	mi := &file_dataplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResult) ProtoMessage() {}

func (x *StopResult) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResult.ProtoReflect.Descriptor instead.
func (*StopResult) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{3}
}

func (x *StopResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PipelineStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	EventsIn      uint64                 `protobuf:"varint,2,opt,name=events_in,json=eventsIn,proto3" json:"events_in,omitempty"`
	EventsOut     uint64                 `protobuf:"varint,3,opt,name=events_out,json=eventsOut,proto3" json:"events_out,omitempty"`
	EventsError   uint64                 `protobuf:"varint,4,opt,name=events_error,json=eventsError,proto3" json:"events_error,omitempty"`
	P99LatencyMs  float64                `protobuf:"fixed64,5,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineStats) Reset() {
	*x = PipelineStats{}
	mi := &file_dataplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineStats) ProtoMessage() {}

func (x *PipelineStats) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineStats.ProtoReflect.Descriptor instead.
func (*PipelineStats) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{4}
}

func (x *PipelineStats) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *PipelineStats) GetEventsIn() uint64 {
	if x != nil {
		return x.EventsIn
	}
	return 0
}

func (x *PipelineStats) GetEventsOut() uint64 {
	if x != nil {
		return x.EventsOut
	}
	return 0
}

func (x *PipelineStats) GetEventsError() uint64 {
	if x != nil {
		return x.EventsError
	}
	return 0
}

func (x *PipelineStats) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

type ModelSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	OnnxArtifact  []byte                 `protobuf:"bytes,2,opt,name=onnx_artifact,json=onnxArtifact,proto3" json:"onnx_artifact,omitempty"`
	Dataset       string                 `protobuf:"bytes,3,opt,name=dataset,proto3" json:"dataset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelSpec) Reset() {
	*x = ModelSpec{}
	mi := &file_dataplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelSpec) ProtoMessage() {}

func (x *ModelSpec) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelSpec.ProtoReflect.Descriptor instead.
func (*ModelSpec) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{5}
}

func (x *ModelSpec) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelSpec) GetOnnxArtifact() []byte {
	if x != nil {
		return x.OnnxArtifact
	}
	return nil
}

func (x *ModelSpec) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

type RuleSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	WasmArtifact  []byte                 `protobuf:"bytes,2,opt,name=wasm_artifact,json=wasmArtifact,proto3" json:"wasm_artifact,omitempty"`
	Dataset       string                 `protobuf:"bytes,3,opt,name=dataset,proto3" json:"dataset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleSpec) Reset() {
	*x = RuleSpec{}
	mi := &file_dataplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSpec) ProtoMessage() {}

func (x *RuleSpec) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSpec.ProtoReflect.Descriptor instead.
func (*RuleSpec) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{6}
}

func (x *RuleSpec) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RuleSpec) GetWasmArtifact() []byte {
	if x != nil {
		return x.WasmArtifact
	}
	return nil
}

func (x *RuleSpec) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

type EventFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datasets      []string               `protobuf:"bytes,1,rep,name=datasets,proto3" json:"datasets,omitempty"`
	EventTypes    []string               `protobuf:"bytes,2,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"` // e.g. "anomaly.detected", "dlq"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFilter) Reset() {
	*x = EventFilter{}
	mi := &file_dataplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFilter) ProtoMessage() {}

func (x *EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFilter.ProtoReflect.Descriptor instead.
func (*EventFilter) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{7}
}

func (x *EventFilter) GetDatasets() []string {
	if x != nil {
		return x.Datasets
	}
	return nil
}

func (x *EventFilter) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Dataset       string                 `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_dataplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{8}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_dataplane_proto protoreflect.FileDescriptor

const file_dataplane_proto_rawDesc = "" +
	"\n" +
	"\x0fdataplane.proto\x12\x15herminas.dataplane.v1\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1c\n" +
	"\n" +
	"PipelineId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\fPipelineSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vyaml_config\x18\x03 \x01(\tR\n" +
	"yamlConfig\"B\n" +
	"\fDeployResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"@\n" +
	"\n" +
	"StopResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb5\x01\n" +
	"\rPipelineStats\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x1b\n" +
	"\tevents_in\x18\x02 \x01(\x04R\beventsIn\x12\x1d\n" +
	"\n" +
	"events_out\x18\x03 \x01(\x04R\teventsOut\x12!\n" +
	"\fevents_error\x18\x04 \x01(\x04R\veventsError\x12$\n" +
	"\x0ep99_latency_ms\x18\x05 \x01(\x01R\fp99LatencyMs\"e\n" +
	"\tModelSpec\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12#\n" +
	"\ronnx_artifact\x18\x02 \x01(\fR\fonnxArtifact\x12\x18\n" +
	"\adataset\x18\x03 \x01(\tR\adataset\"b\n" +
	"\bRuleSpec\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12#\n" +
	"\rwasm_artifact\x18\x02 \x01(\fR\fwasmArtifact\x12\x18\n" +
	"\adataset\x18\x03 \x01(\tR\adataset\"J\n" +
	"\vEventFilter\x12\x1a\n" +
	"\bdatasets\x18\x01 \x03(\tR\bdatasets\x12\x1f\n" +
	"\vevent_types\x18\x02 \x03(\tR\n" +
	"eventTypes\"\x9e\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\adataset\x18\x02 \x01(\tR\adataset\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12F\n" +
	"\bmetadata\x18\x06 \x03(\v2*.herminas.dataplane.v1.Event.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xea\x04\n" +
	"\tDataPlane\x12Z\n" +
	"\x0eDeployPipeline\x12#.herminas.dataplane.v1.PipelineSpec\x1a#.herminas.dataplane.v1.DeployResult\x12T\n" +
	"\fStopPipeline\x12!.herminas.dataplane.v1.PipelineId\x1a!.herminas.dataplane.v1.StopResult\x12[\n" +
	"\x10GetPipelineStats\x12!.herminas.dataplane.v1.PipelineId\x1a$.herminas.dataplane.v1.PipelineStats\x12T\n" +
	"\vDeployModel\x12 .herminas.dataplane.v1.ModelSpec\x1a#.herminas.dataplane.v1.DeployResult\x12R\n" +
	"\n" +
	"DeployRule\x12\x1f.herminas.dataplane.v1.RuleSpec\x1a#.herminas.dataplane.v1.DeployResult\x12R\n" +
	"\fStreamEvents\x12\".herminas.dataplane.v1.EventFilter\x1a\x1c.herminas.dataplane.v1.Event0\x01\x12P\n" +
	"\tGetHealth\x12!.herminas.common.v1.HealthRequest\x1a .herminas.common.v1.HealthStatusB#Z!herminas/kernel/proto/dataplanepbb\x06proto3"

var (
	file_dataplane_proto_rawDescOnce sync.Once
	file_dataplane_proto_rawDescData []byte
)

func file_dataplane_proto_rawDescGZIP() []byte {
	file_dataplane_proto_rawDescOnce.Do(func() {
		file_dataplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dataplane_proto_rawDesc), len(file_dataplane_proto_rawDesc)))
	})
	return file_dataplane_proto_rawDescData
}

var file_dataplane_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_dataplane_proto_goTypes = []any{
	(*PipelineId)(nil),             // 0: herminas.dataplane.v1.PipelineId
	(*PipelineSpec)(nil),           // 1: herminas.dataplane.v1.PipelineSpec
	(*DeployResult)(nil),           // 2: herminas.dataplane.v1.DeployResult
	(*StopResult)(nil),             // 3: herminas.dataplane.v1.StopResult
	(*PipelineStats)(nil),          // 4: herminas.dataplane.v1.PipelineStats
	(*ModelSpec)(nil),              // 5: herminas.dataplane.v1.ModelSpec
	(*RuleSpec)(nil),               // 6: herminas.dataplane.v1.RuleSpec
	(*EventFilter)(nil),            // 7: herminas.dataplane.v1.EventFilter
	(*Event)(nil),                  // 8: herminas.dataplane.v1.Event
	nil,                            // 9: herminas.dataplane.v1.Event.MetadataEntry
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
	(*commonpb.HealthRequest)(nil), // 11: herminas.common.v1.HealthRequest
	(*commonpb.HealthStatus)(nil),  // 12: herminas.common.v1.HealthStatus
}
var file_dataplane_proto_depIdxs = []int32{
	10, // 0: herminas.dataplane.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 1: herminas.dataplane.v1.Event.metadata:type_name -> herminas.dataplane.v1.Event.MetadataEntry
	1,  // 2: herminas.dataplane.v1.DataPlane.DeployPipeline:input_type -> herminas.dataplane.v1.PipelineSpec
	0,  // 3: herminas.dataplane.v1.DataPlane.StopPipeline:input_type -> herminas.dataplane.v1.PipelineId
	0,  // 4: herminas.dataplane.v1.DataPlane.GetPipelineStats:input_type -> herminas.dataplane.v1.PipelineId
	5,  // 5: herminas.dataplane.v1.DataPlane.DeployModel:input_type -> herminas.dataplane.v1.ModelSpec
	6,  // 6: herminas.dataplane.v1.DataPlane.DeployRule:input_type -> herminas.dataplane.v1.RuleSpec
	7,  // 7: herminas.dataplane.v1.DataPlane.StreamEvents:input_type -> herminas.dataplane.v1.EventFilter
	11, // 8: herminas.dataplane.v1.DataPlane.GetHealth:input_type -> herminas.common.v1.HealthRequest
	2,  // 9: herminas.dataplane.v1.DataPlane.DeployPipeline:output_type -> herminas.dataplane.v1.DeployResult
	3,  // 10: herminas.dataplane.v1.DataPlane.StopPipeline:output_type -> herminas.dataplane.v1.StopResult
	4,  // 11: herminas.dataplane.v1.DataPlane.GetPipelineStats:output_type -> herminas.dataplane.v1.PipelineStats
	2,  // 12: herminas.dataplane.v1.DataPlane.DeployModel:output_type -> herminas.dataplane.v1.DeployResult
	2,  // 13: herminas.dataplane.v1.DataPlane.DeployRule:output_type -> herminas.dataplane.v1.DeployResult
	8,  // 14: herminas.dataplane.v1.DataPlane.StreamEvents:output_type -> herminas.dataplane.v1.Event
	12, // 15: herminas.dataplane.v1.DataPlane.GetHealth:output_type -> herminas.common.v1.HealthStatus
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_dataplane_proto_init() }
func file_dataplane_proto_init() {
	if File_dataplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dataplane_proto_rawDesc), len(file_dataplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dataplane_proto_goTypes,
		DependencyIndexes: file_dataplane_proto_depIdxs,
		MessageInfos:      file_dataplane_proto_msgTypes,
	}.Build()
	File_dataplane_proto = out.File
	file_dataplane_proto_goTypes = nil
	file_dataplane_proto_depIdxs = nil
}
