// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: dataplane.proto

// Go control plane -> Rust data plane. Go is always the client here
// (cahier des charges §6.3); the Rust server lives in rust/protocol/.
//
// Only GetHealth has a real implementation as of M0.3 — it exists to prove
// the gRPC plumbing works end to end (protoc -> stubs in 3 languages ->
// real server -> real client -> latency benchmark). The rest are the
// contracts the pipeline manager (M3.2), ML deploy (M4.3) and WASM rules
// (M6.2) will implement against; calling them today returns UNIMPLEMENTED.

package dataplanepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	commonpb "herminas/kernel/proto/commonpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataPlane_DeployPipeline_FullMethodName   = "/herminas.dataplane.v1.DataPlane/DeployPipeline"
	DataPlane_StopPipeline_FullMethodName     = "/herminas.dataplane.v1.DataPlane/StopPipeline"
	DataPlane_GetPipelineStats_FullMethodName = "/herminas.dataplane.v1.DataPlane/GetPipelineStats"
	DataPlane_DeployModel_FullMethodName      = "/herminas.dataplane.v1.DataPlane/DeployModel"
	DataPlane_DeployRule_FullMethodName       = "/herminas.dataplane.v1.DataPlane/DeployRule"
	DataPlane_StreamEvents_FullMethodName     = "/herminas.dataplane.v1.DataPlane/StreamEvents"
	DataPlane_GetHealth_FullMethodName        = "/herminas.dataplane.v1.DataPlane/GetHealth"
)

// DataPlaneClient is the client API for DataPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataPlaneClient interface {
	DeployPipeline(ctx context.Context, in *PipelineSpec, opts ...grpc.CallOption) (*DeployResult, error)
	StopPipeline(ctx context.Context, in *PipelineId, opts ...grpc.CallOption) (*StopResult, error)
	GetPipelineStats(ctx context.Context, in *PipelineId, opts ...grpc.CallOption) (*PipelineStats, error)
	DeployModel(ctx context.Context, in *ModelSpec, opts ...grpc.CallOption) (*DeployResult, error)
	DeployRule(ctx context.Context, in *RuleSpec, opts ...grpc.CallOption) (*DeployResult, error)
	StreamEvents(ctx context.Context, in *EventFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	GetHealth(ctx context.Context, in *commonpb.HealthRequest, opts ...grpc.CallOption) (*commonpb.HealthStatus, error)
}

type dataPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewDataPlaneClient(cc grpc.ClientConnInterface) DataPlaneClient {
	return &dataPlaneClient{cc}
}

func (c *dataPlaneClient) DeployPipeline(ctx context.Context, in *PipelineSpec, opts ...grpc.CallOption) (*DeployResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployResult)
	err := c.cc.Invoke(ctx, DataPlane_DeployPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneClient) StopPipeline(ctx context.Context, in *PipelineId, opts ...grpc.CallOption) (*StopResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResult)
	err := c.cc.Invoke(ctx, DataPlane_StopPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneClient) GetPipelineStats(ctx context.Context, in *PipelineId, opts ...grpc.CallOption) (*PipelineStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PipelineStats)
	err := c.cc.Invoke(ctx, DataPlane_GetPipelineStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneClient) DeployModel(ctx context.Context, in *ModelSpec, opts ...grpc.CallOption) (*DeployResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployResult)
	err := c.cc.Invoke(ctx, DataPlane_DeployModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneClient) DeployRule(ctx context.Context, in *RuleSpec, opts ...grpc.CallOption) (*DeployResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployResult)
	err := c.cc.Invoke(ctx, DataPlane_DeployRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneClient) StreamEvents(ctx context.Context, in *EventFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataPlane_ServiceDesc.Streams[0], DataPlane_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventFilter, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlane_StreamEventsClient = grpc.ServerStreamingClient[Event]

func (c *dataPlaneClient) GetHealth(ctx context.Context, in *commonpb.HealthRequest, opts ...grpc.CallOption) (*commonpb.HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.HealthStatus)
	err := c.cc.Invoke(ctx, DataPlane_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataPlaneServer is the server API for DataPlane service.
// All implementations must embed UnimplementedDataPlaneServer
// for forward compatibility.
type DataPlaneServer interface {
	DeployPipeline(context.Context, *PipelineSpec) (*DeployResult, error)
	StopPipeline(context.Context, *PipelineId) (*StopResult, error)
	GetPipelineStats(context.Context, *PipelineId) (*PipelineStats, error)
	DeployModel(context.Context, *ModelSpec) (*DeployResult, error)
	DeployRule(context.Context, *RuleSpec) (*DeployResult, error)
	StreamEvents(*EventFilter, grpc.ServerStreamingServer[Event]) error
	GetHealth(context.Context, *commonpb.HealthRequest) (*commonpb.HealthStatus, error)
	mustEmbedUnimplementedDataPlaneServer()
}

// UnimplementedDataPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataPlaneServer struct{}

func (UnimplementedDataPlaneServer) DeployPipeline(context.Context, *PipelineSpec) (*DeployResult, error) {
	return nil, status.Error(codes.Unimplemented, "method DeployPipeline not implemented")
}
func (UnimplementedDataPlaneServer) StopPipeline(context.Context, *PipelineId) (*StopResult, error) {
	return nil, status.Error(codes.Unimplemented, "method StopPipeline not implemented")
}
func (UnimplementedDataPlaneServer) GetPipelineStats(context.Context, *PipelineId) (*PipelineStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPipelineStats not implemented")
}
func (UnimplementedDataPlaneServer) DeployModel(context.Context, *ModelSpec) (*DeployResult, error) {
	return nil, status.Error(codes.Unimplemented, "method DeployModel not implemented")
}
func (UnimplementedDataPlaneServer) DeployRule(context.Context, *RuleSpec) (*DeployResult, error) {
	return nil, status.Error(codes.Unimplemented, "method DeployRule not implemented")
}
func (UnimplementedDataPlaneServer) StreamEvents(*EventFilter, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedDataPlaneServer) GetHealth(context.Context, *commonpb.HealthRequest) (*commonpb.HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedDataPlaneServer) mustEmbedUnimplementedDataPlaneServer() {}
func (UnimplementedDataPlaneServer) testEmbeddedByValue()                   {}

// UnsafeDataPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataPlaneServer will
// result in compilation errors.
type UnsafeDataPlaneServer interface {
	mustEmbedUnimplementedDataPlaneServer()
}

func RegisterDataPlaneServer(s grpc.ServiceRegistrar, srv DataPlaneServer) {
	// If the following call panics, it indicates UnimplementedDataPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataPlane_ServiceDesc, srv)
}

func _DataPlane_DeployPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).DeployPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlane_DeployPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).DeployPipeline(ctx, req.(*PipelineSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlane_StopPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).StopPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlane_StopPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).StopPipeline(ctx, req.(*PipelineId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlane_GetPipelineStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).GetPipelineStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlane_GetPipelineStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).GetPipelineStats(ctx, req.(*PipelineId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlane_DeployModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).DeployModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlane_DeployModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).DeployModel(ctx, req.(*ModelSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlane_DeployRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).DeployRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlane_DeployRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).DeployRule(ctx, req.(*RuleSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlane_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataPlaneServer).StreamEvents(m, &grpc.GenericServerStream[EventFilter, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlane_StreamEventsServer = grpc.ServerStreamingServer[Event]

func _DataPlane_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonpb.HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlane_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).GetHealth(ctx, req.(*commonpb.HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataPlane_ServiceDesc is the grpc.ServiceDesc for DataPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "herminas.dataplane.v1.DataPlane",
	HandlerType: (*DataPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeployPipeline",
			Handler:    _DataPlane_DeployPipeline_Handler,
		},
		{
			MethodName: "StopPipeline",
			Handler:    _DataPlane_StopPipeline_Handler,
		},
		{
			MethodName: "GetPipelineStats",
			Handler:    _DataPlane_GetPipelineStats_Handler,
		},
		{
			MethodName: "DeployModel",
			Handler:    _DataPlane_DeployModel_Handler,
		},
		{
			MethodName: "DeployRule",
			Handler:    _DataPlane_DeployRule_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _DataPlane_GetHealth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _DataPlane_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dataplane.proto",
}
