// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: intelligence.proto

// Go control plane -> Python intelligence. Go is always the client
// (cahier des charges §6.4); the Python server lives in
// python/src/herminas_intelligence/grpc_server.py.
//
// Only GetHealth has a real implementation as of M0.3, for the same reason
// as dataplane.proto: proving the gRPC plumbing end to end. NL->SQL (M4.1),
// training (M4.3) and forecasting (M4.3) implement the rest; calling them
// today returns UNIMPLEMENTED.

package intelligencepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	commonpb "herminas/kernel/proto/commonpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NLQuery struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Question        string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Language        string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"` // "fr" | "en"
	AllowedDatasets []string               `protobuf:"bytes,3,rep,name=allowed_datasets,json=allowedDatasets,proto3" json:"allowed_datasets,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NLQuery) Reset() {
	*x = NLQuery{}
	mi := &file_intelligence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NLQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NLQuery) ProtoMessage() {}

func (x *NLQuery) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NLQuery.ProtoReflect.Descriptor instead.
func (*NLQuery) Descriptor() ([]byte, []int) {
	return file_intelligence_proto_rawDescGZIP(), []int{0}
}

func (x *NLQuery) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *NLQuery) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *NLQuery) GetAllowedDatasets() []string {
	if x != nil {
		return x.AllowedDatasets
	}
	return nil
}

type SQLCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	Explanation   string                 `protobuf:"bytes,2,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Valid         bool                   `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLCandidate) Reset() {
	*x = SQLCandidate{}
	mi := &file_intelligence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLCandidate) ProtoMessage() {}

func (x *SQLCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLCandidate.ProtoReflect.Descriptor instead.
func (*SQLCandidate) Descriptor() ([]byte, []int) {
	return file_intelligence_proto_rawDescGZIP(), []int{1}
}

func (x *SQLCandidate) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *SQLCandidate) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *SQLCandidate) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type ModelId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelId) Reset() {
	*x = ModelId{}
	mi := &file_intelligence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelId) ProtoMessage() {}

func (x *ModelId) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelId.ProtoReflect.Descriptor instead.
func (*ModelId) Descriptor() ([]byte, []int) {
	return file_intelligence_proto_rawDescGZIP(), []int{2}
}

func (x *ModelId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       string                 `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	ModelType     string                 `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"` // "anomaly" | "fraud" | "forecast"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainRequest) Reset() {
	*x = TrainRequest{}
	mi := &file_intelligence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRequest) ProtoMessage() {}

func (x *TrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRequest.ProtoReflect.Descriptor instead.
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return file_intelligence_proto_rawDescGZIP(), []int{3}
}

func (x *TrainRequest) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *TrainRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

type TrainProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      float64                `protobuf:"fixed64,1,opt,name=progress,proto3" json:"progress,omitempty"` // 0.0-1.0
	Stage         string                 `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainProgress) Reset() {
	*x = TrainProgress{}
	mi := &file_intelligence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainProgress) ProtoMessage() {}

func (x *TrainProgress) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainProgress.ProtoReflect.Descriptor instead.
func (*TrainProgress) Descriptor() ([]byte, []int) {
	return file_intelligence_proto_rawDescGZIP(), []int{4}
}

func (x *TrainProgress) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TrainProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *TrainProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ONNXArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	OnnxBytes     []byte                 `protobuf:"bytes,2,opt,name=onnx_bytes,json=onnxBytes,proto3" json:"onnx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ONNXArtifact) Reset() {
	*x = ONNXArtifact{}
	mi := &file_intelligence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ONNXArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ONNXArtifact) ProtoMessage() {}

func (x *ONNXArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ONNXArtifact.ProtoReflect.Descriptor instead.
func (*ONNXArtifact) Descriptor() ([]byte, []int) {
	return file_intelligence_proto_rawDescGZIP(), []int{5}
}

func (x *ONNXArtifact) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ONNXArtifact) GetOnnxBytes() []byte {
	if x != nil {
		return x.OnnxBytes
	}
	return nil
}

type ForecastRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Dataset        string                 `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Metric         string                 `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	HorizonMinutes uint32                 `protobuf:"varint,3,opt,name=horizon_minutes,json=horizonMinutes,proto3" json:"horizon_minutes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ForecastRequest) Reset() {
	*x = ForecastRequest{}
	mi := &file_intelligence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastRequest) ProtoMessage() {}

func (x *ForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastRequest.ProtoReflect.Descriptor instead.
func (*ForecastRequest) Descriptor() ([]byte, []int) {
	return file_intelligence_proto_rawDescGZIP(), []int{6}
}

func (x *ForecastRequest) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *ForecastRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *ForecastRequest) GetHorizonMinutes() uint32 {
	if x != nil {
		return x.HorizonMinutes
	}
	return 0
}

type ForecastResult struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Values        []float64                `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	Timestamps    []*timestamppb.Timestamp `protobuf:"bytes,2,rep,name=timestamps,proto3" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForecastResult) Reset() {
	*x = ForecastResult{}
	mi := &file_intelligence_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastResult) ProtoMessage() {}

func (x *ForecastResult) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastResult.ProtoReflect.Descriptor instead.
func (*ForecastResult) Descriptor() ([]byte, []int) {
	return file_intelligence_proto_rawDescGZIP(), []int{7}
}

func (x *ForecastResult) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ForecastResult) GetTimestamps() []*timestamppb.Timestamp {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

var File_intelligence_proto protoreflect.FileDescriptor

const file_intelligence_proto_rawDesc = "" +
	"\n" +
	"\x12intelligence.proto\x12\x18herminas.intelligence.v1\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"l\n" +
	"\aNLQuery\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12)\n" +
	"\x10allowed_datasets\x18\x03 \x03(\tR\x0fallowedDatasets\"X\n" +
	"\fSQLCandidate\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12 \n" +
	"\vexplanation\x18\x02 \x01(\tR\vexplanation\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\"\x19\n" +
	"\aModelId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\fTrainRequest\x12\x18\n" +
	"\adataset\x18\x01 \x01(\tR\adataset\x12\x1d\n" +
	"\n" +
	"model_type\x18\x02 \x01(\tR\tmodelType\"[\n" +
	"\rTrainProgress\x12\x1a\n" +
	"\bprogress\x18\x01 \x01(\x01R\bprogress\x12\x14\n" +
	"\x05stage\x18\x02 \x01(\tR\x05stage\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"H\n" +
	"\fONNXArtifact\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"onnx_bytes\x18\x02 \x01(\fR\tonnxBytes\"l\n" +
	"\x0fForecastRequest\x12\x18\n" +
	"\adataset\x18\x01 \x01(\tR\adataset\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\x12'\n" +
	"\x0fhorizon_minutes\x18\x03 \x01(\rR\x0ehorizonMinutes\"d\n" +
	"\x0eForecastResult\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\x12:\n" +
	"\n" +
	"timestamps\x18\x02 \x03(\v2\x1a.google.protobuf.TimestampR\n" +
	"timestamps2\xd5\x03\n" +
	"\fIntelligence\x12X\n" +
	"\vTranslateNL\x12!.herminas.intelligence.v1.NLQuery\x1a&.herminas.intelligence.v1.SQLCandidate\x12_\n" +
	"\n" +
	"TrainModel\x12&.herminas.intelligence.v1.TrainRequest\x1a'.herminas.intelligence.v1.TrainProgress0\x01\x12W\n" +
	"\n" +
	"ExportONNX\x12!.herminas.intelligence.v1.ModelId\x1a&.herminas.intelligence.v1.ONNXArtifact\x12_\n" +
	"\bForecast\x12).herminas.intelligence.v1.ForecastRequest\x1a(.herminas.intelligence.v1.ForecastResult\x12P\n" +
	"\tGetHealth\x12!.herminas.common.v1.HealthRequest\x1a .herminas.common.v1.HealthStatusB&Z$herminas/kernel/proto/intelligencepbb\x06proto3"

var (
	file_intelligence_proto_rawDescOnce sync.Once
	file_intelligence_proto_rawDescData []byte
)

func file_intelligence_proto_rawDescGZIP() []byte {
	file_intelligence_proto_rawDescOnce.Do(func() {
		file_intelligence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_intelligence_proto_rawDesc), len(file_intelligence_proto_rawDesc)))
	})
	return file_intelligence_proto_rawDescData
}

var file_intelligence_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_intelligence_proto_goTypes = []any{
	(*NLQuery)(nil),                // 0: herminas.intelligence.v1.NLQuery
	(*SQLCandidate)(nil),           // 1: herminas.intelligence.v1.SQLCandidate
	(*ModelId)(nil),                // 2: herminas.intelligence.v1.ModelId
	(*TrainRequest)(nil),           // 3: herminas.intelligence.v1.TrainRequest
	(*TrainProgress)(nil),          // 4: herminas.intelligence.v1.TrainProgress
	(*ONNXArtifact)(nil),           // 5: herminas.intelligence.v1.ONNXArtifact
	(*ForecastRequest)(nil),        // 6: herminas.intelligence.v1.ForecastRequest
	(*ForecastResult)(nil),         // 7: herminas.intelligence.v1.ForecastResult
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
	(*commonpb.HealthRequest)(nil), // 9: herminas.common.v1.HealthRequest
	(*commonpb.HealthStatus)(nil),  // 10: herminas.common.v1.HealthStatus
}
var file_intelligence_proto_depIdxs = []int32{
	8,  // 0: herminas.intelligence.v1.ForecastResult.timestamps:type_name -> google.protobuf.Timestamp
	0,  // 1: herminas.intelligence.v1.Intelligence.TranslateNL:input_type -> herminas.intelligence.v1.NLQuery
	3,  // 2: herminas.intelligence.v1.Intelligence.TrainModel:input_type -> herminas.intelligence.v1.TrainRequest
	2,  // 3: herminas.intelligence.v1.Intelligence.ExportONNX:input_type -> herminas.intelligence.v1.ModelId
	6,  // 4: herminas.intelligence.v1.Intelligence.Forecast:input_type -> herminas.intelligence.v1.ForecastRequest
	9,  // 5: herminas.intelligence.v1.Intelligence.GetHealth:input_type -> herminas.common.v1.HealthRequest
	1,  // 6: herminas.intelligence.v1.Intelligence.TranslateNL:output_type -> herminas.intelligence.v1.SQLCandidate
	4,  // 7: herminas.intelligence.v1.Intelligence.TrainModel:output_type -> herminas.intelligence.v1.TrainProgress
	5,  // 8: herminas.intelligence.v1.Intelligence.ExportONNX:output_type -> herminas.intelligence.v1.ONNXArtifact
	7,  // 9: herminas.intelligence.v1.Intelligence.Forecast:output_type -> herminas.intelligence.v1.ForecastResult
	10, // 10: herminas.intelligence.v1.Intelligence.GetHealth:output_type -> herminas.common.v1.HealthStatus
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_intelligence_proto_init() }
func file_intelligence_proto_init() {
	if File_intelligence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_intelligence_proto_rawDesc), len(file_intelligence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_intelligence_proto_goTypes,
		DependencyIndexes: file_intelligence_proto_depIdxs,
		MessageInfos:      file_intelligence_proto_msgTypes,
	}.Build()
	File_intelligence_proto = out.File
	file_intelligence_proto_goTypes = nil
	file_intelligence_proto_depIdxs = nil
}
