// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: intelligence.proto

// Go control plane -> Python intelligence. Go is always the client
// (cahier des charges §6.4); the Python server lives in
// python/src/herminas_intelligence/grpc_server.py.
//
// Only GetHealth has a real implementation as of M0.3, for the same reason
// as dataplane.proto: proving the gRPC plumbing end to end. NL->SQL (M4.1),
// training (M4.3) and forecasting (M4.3) implement the rest; calling them
// today returns UNIMPLEMENTED.

package intelligencepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	commonpb "herminas/kernel/proto/commonpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Intelligence_TranslateNL_FullMethodName = "/herminas.intelligence.v1.Intelligence/TranslateNL"
	Intelligence_TrainModel_FullMethodName  = "/herminas.intelligence.v1.Intelligence/TrainModel"
	Intelligence_ExportONNX_FullMethodName  = "/herminas.intelligence.v1.Intelligence/ExportONNX"
	Intelligence_Forecast_FullMethodName    = "/herminas.intelligence.v1.Intelligence/Forecast"
	Intelligence_GetHealth_FullMethodName   = "/herminas.intelligence.v1.Intelligence/GetHealth"
)

// IntelligenceClient is the client API for Intelligence service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntelligenceClient interface {
	TranslateNL(ctx context.Context, in *NLQuery, opts ...grpc.CallOption) (*SQLCandidate, error)
	TrainModel(ctx context.Context, in *TrainRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrainProgress], error)
	ExportONNX(ctx context.Context, in *ModelId, opts ...grpc.CallOption) (*ONNXArtifact, error)
	Forecast(ctx context.Context, in *ForecastRequest, opts ...grpc.CallOption) (*ForecastResult, error)
	GetHealth(ctx context.Context, in *commonpb.HealthRequest, opts ...grpc.CallOption) (*commonpb.HealthStatus, error)
}

type intelligenceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntelligenceClient(cc grpc.ClientConnInterface) IntelligenceClient {
	return &intelligenceClient{cc}
}

func (c *intelligenceClient) TranslateNL(ctx context.Context, in *NLQuery, opts ...grpc.CallOption) (*SQLCandidate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SQLCandidate)
	err := c.cc.Invoke(ctx, Intelligence_TranslateNL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceClient) TrainModel(ctx context.Context, in *TrainRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrainProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Intelligence_ServiceDesc.Streams[0], Intelligence_TrainModel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrainRequest, TrainProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Intelligence_TrainModelClient = grpc.ServerStreamingClient[TrainProgress]

func (c *intelligenceClient) ExportONNX(ctx context.Context, in *ModelId, opts ...grpc.CallOption) (*ONNXArtifact, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ONNXArtifact)
	err := c.cc.Invoke(ctx, Intelligence_ExportONNX_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceClient) Forecast(ctx context.Context, in *ForecastRequest, opts ...grpc.CallOption) (*ForecastResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForecastResult)
	err := c.cc.Invoke(ctx, Intelligence_Forecast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceClient) GetHealth(ctx context.Context, in *commonpb.HealthRequest, opts ...grpc.CallOption) (*commonpb.HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.HealthStatus)
	err := c.cc.Invoke(ctx, Intelligence_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntelligenceServer is the server API for Intelligence service.
// All implementations must embed UnimplementedIntelligenceServer
// for forward compatibility.
type IntelligenceServer interface {
	TranslateNL(context.Context, *NLQuery) (*SQLCandidate, error)
	TrainModel(*TrainRequest, grpc.ServerStreamingServer[TrainProgress]) error
	ExportONNX(context.Context, *ModelId) (*ONNXArtifact, error)
	Forecast(context.Context, *ForecastRequest) (*ForecastResult, error)
	GetHealth(context.Context, *commonpb.HealthRequest) (*commonpb.HealthStatus, error)
	mustEmbedUnimplementedIntelligenceServer()
}

// UnimplementedIntelligenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntelligenceServer struct{}

func (UnimplementedIntelligenceServer) TranslateNL(context.Context, *NLQuery) (*SQLCandidate, error) {
	return nil, status.Error(codes.Unimplemented, "method TranslateNL not implemented")
}
func (UnimplementedIntelligenceServer) TrainModel(*TrainRequest, grpc.ServerStreamingServer[TrainProgress]) error {
	return status.Error(codes.Unimplemented, "method TrainModel not implemented")
}
func (UnimplementedIntelligenceServer) ExportONNX(context.Context, *ModelId) (*ONNXArtifact, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportONNX not implemented")
}
func (UnimplementedIntelligenceServer) Forecast(context.Context, *ForecastRequest) (*ForecastResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Forecast not implemented")
}
func (UnimplementedIntelligenceServer) GetHealth(context.Context, *commonpb.HealthRequest) (*commonpb.HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedIntelligenceServer) mustEmbedUnimplementedIntelligenceServer() {}
func (UnimplementedIntelligenceServer) testEmbeddedByValue()                      {}

// UnsafeIntelligenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntelligenceServer will
// result in compilation errors.
type UnsafeIntelligenceServer interface {
	mustEmbedUnimplementedIntelligenceServer()
}

func RegisterIntelligenceServer(s grpc.ServiceRegistrar, srv IntelligenceServer) {
	// If the following call panics, it indicates UnimplementedIntelligenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Intelligence_ServiceDesc, srv)
}

func _Intelligence_TranslateNL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NLQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServer).TranslateNL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Intelligence_TranslateNL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServer).TranslateNL(ctx, req.(*NLQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Intelligence_TrainModel_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TrainRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IntelligenceServer).TrainModel(m, &grpc.GenericServerStream[TrainRequest, TrainProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Intelligence_TrainModelServer = grpc.ServerStreamingServer[TrainProgress]

func _Intelligence_ExportONNX_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServer).ExportONNX(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Intelligence_ExportONNX_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServer).ExportONNX(ctx, req.(*ModelId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Intelligence_Forecast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForecastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServer).Forecast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Intelligence_Forecast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServer).Forecast(ctx, req.(*ForecastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Intelligence_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonpb.HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Intelligence_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServer).GetHealth(ctx, req.(*commonpb.HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Intelligence_ServiceDesc is the grpc.ServiceDesc for Intelligence service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Intelligence_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "herminas.intelligence.v1.Intelligence",
	HandlerType: (*IntelligenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TranslateNL",
			Handler:    _Intelligence_TranslateNL_Handler,
		},
		{
			MethodName: "ExportONNX",
			Handler:    _Intelligence_ExportONNX_Handler,
		},
		{
			MethodName: "Forecast",
			Handler:    _Intelligence_Forecast_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _Intelligence_GetHealth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TrainModel",
			Handler:       _Intelligence_TrainModel_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "intelligence.proto",
}
